<a href="https://colab.research.google.com/github/Taheri1400/data_analysing_Pandas_numpy_projects/blob/main/project1_step2_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
فروش شکلات
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این گام از پروژه قصد داریم برای شکلات‌ها با توجه به برخی مشخصات‌شان و تحقیق‌هایی که کرده‌ایم قیمت تعیین کنیم. برای این کار از داده‌هایی که در گام قبل پردازش کرده‌ایم استفاده کرده و سپس مرحله به مرحله سعی می‌کنیم تخمین قیمت خود را بهتر کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در گام پیشین پروژه یک سری پیش‌پردازش‌هایی روی مجموعه‌داده‌ی شکلات‌ها انجام داده و حاصل را در فایل <code>chocolate_preprocessed.csv</code> ذخیره کردید. بنابراین ابتدا در سلول زیر این فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>

In [1]:
from google.colab import files
uploaded= files.upload()

Saving chocolate_preprocessed.csv to chocolate_preprocessed.csv

In [74]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_preprocessed.csv')
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,3.75,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,2.75,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,3.00,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,3.50,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,3.50,Blend,Peru
...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,2011,70.0,Austria,3.75,Blend,Peru
1791,Zotter,Congo,2011,65.0,Austria,3.00,Forastero,Congo
1792,Zotter,Kerala State,2011,65.0,Austria,3.50,Forastero,India
1793,Zotter,Kerala State,2011,62.0,Austria,3.25,Blend,India
1794,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,3.00,Blend,Brazil

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که بعد از کمی تحقیق متوجه شده‌ایم که قیمت یک شکلات با درصد امتیاز آن توسط متخصصان رابطه‌ی مستقیم دارد. خوشبختانه این امتیاز در مشخصات داده‌های ما وجود دارد، اما مسئله این است که این امتیازها به‌صورت درصد نیستند. پس در این مرحله از شما می‌خواهیم تا مقادیر ستون <code>Rating</code> را به گونه‌ای تغییر مقیاس دهید که بالاترین مقدار آن ۱۰۰ باشد و سایر مقادیر نیز دقیقاً به همان نسبت تغییر کنند. به‌عنوان مثال فرض کنید بیشترین مقداری که در این ستون وجود دارد برابر ۴ باشد. در این‌صورت برای تبدیل ۴ به ۱۰۰ باید آن را ضرب در ۲۵ کنید. پس تمام مقادیر این ستون باید ضرب در ۲۵ شوند. توجه داشته باشید که در نهایت نوع ستون شما باید <code>float</code> باشد.
</font>
</p>

In [75]:
df['Rating']=df['Rating'].apply(lambda x: ((100/df['Rating'].max())*x))
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru
...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru
1791,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo
1792,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India
1793,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India
1794,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
بعد از کمی تحقیق مشخص شد که قیمت ۱۰۰ گرم کاکائوی خالص با بالاترین کیفیت ۲۵۰۰۰۰ تومان است. بنابراین می‌توانیم با ضرب درصد کاکائو (ستون <code>Cocoa Percent</code>) در قیمت صد گرم آن (عدد ۲۵) و همچنین درصد امتیاز (ستون <code>Rating</code>)،‌ قیمت صد گرم از یک نوع شکلات را تخمین بزنیم.
در این قسمت به کمک فرمول زیر قیمت صد گرم از  هر نوع شکلات را محاسبه کرده و در ستون جدیدی به نام <code>price(100g)</code> ذخیره کنید.
<br>
<center>
قیمت صد گرم = درصد کاکائو × امتیاز × ۲۵
</center>
</font>
</p>

In [76]:
df['price(100g)'] = df.apply(lambda x: 25*(x['Rating'])*(x['Cocoa Percent']),axis=1)
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
1791,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
1792,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
1793,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0
1794,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil,97500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که متوجه شده‌ایم شکلات‌های تلخ گران‌تر و پرسودتر هستند. بنابراین قصد داریم ادامه‌ی تمرین را تنها با این نوع از شکلات‌ها پیش ببریم.
در این قسمت شکلات‌هایی که درصد کاکائو آن‌ها بیشتر از ۷۰ درصد است را به‌عنوان شکلات تلخ در نظر گرفته و در مجموعه‌داده‌ی جدیدی با نام <code>dark_chocolates</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [77]:
dark_chocolates =df[df['Cocoa Percent']>70]
dark_chocolates.reset_index(inplace=True, drop=True)
dark_chocolates

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Adi,"Vanua Levu, Toto-A",2011,80.0,Fiji,65.0,Trinitario,Fiji,130000.0
1,Adi,Vanua Levu,2011,88.0,Fiji,70.0,Trinitario,Fiji,154000.0
2,Adi,"Vanua Levu, Ami-Ami-CA",2011,72.0,Fiji,70.0,Trinitario,Fiji,126000.0
3,Akesson's (Pralus),"Bali (west), Sukrama Family, Melaya area",2011,75.0,Switzerland,75.0,Trinitario,Indonesia,140625.0
4,Akesson's (Pralus),"Madagascar, Ambolikapiky P.",2010,75.0,Switzerland,55.0,Criollo,Madagascar,103125.0
...,...,...,...,...,...,...,...,...,...
790,Zotter,Raw,2014,80.0,Austria,55.0,Blend,Other,110000.0
791,Zotter,"Bocas del Toro, Cocabo Co-op",2012,72.0,Austria,70.0,Blend,Panama,126000.0
792,Zotter,El Oro,2012,75.0,Austria,60.0,Forastero (Nacional),Ecuador,112500.0
793,Zotter,Huiwani Coop,2012,75.0,Austria,60.0,"Criollo, Trinitario",Papua New Guinea,112500.0
794,Zotter,El Ceibo Coop,2012,90.0,Austria,65.0,Blend,Bolivia,146250.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
نوع دانه‌ی استفاده شده برای ساخت شکلات نیز در مرغوبیت آن تاثیر مستقیم می‌گذارد. برای مثال یکی از بهترین دانه‌های شکلات از نوع <code>Trinitario</code> است.
به همین دلیل تصمیم گرفته‌ایم قیمت شکلات‌های تلخی (دیتافریم <code>dark_chocolates</code>) که از این دانه استفاده کرده‌اند را ۱۰ درصد افزایش دهیم.
<br>
ابتدا در متغیر <code>has_Trinitario</code> برای هر شکلات مشخص کنید که آیا در نام دانه‌های مختلف این شکلات (ستون <code>Bean Type</code>) اسمی از <code>Trinitario</code> برده شده است یا خیر. یعنی خروجی شما باید به شکل یک آرایه به طول دیتافریم شکلات‌های تلخ باشد که با توجه به وجود یا عدم وجود این نوع دانه در آن شکلات مقدار <code>True</code> یا <code>False</code> داشته باشد.
</font>
</p>

In [78]:
#has_Trinitario = dark_chocolates['Bean Type']=='Trinitario'
has_Trinitario=dark_chocolates['Bean Type'].str.contains('Trinitario')
has_Trinitario

0       True
1       True
2       True
3       True
4      False
       ...
790    False
791    False
792    False
793     True
794    False
Name: Bean Type, Length: 795, dtype: bool

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون می‌توانید از آرایه‌ی <code>has_Trinitario</code> استفاده کرده و قیمت آن ردیف‌هایی که در این آرایه مقدار <code>True</code> دارند را ۱۰ درصد افزایش دهید.
</font>
</p>

In [79]:
dark_chocolates.loc[has_Trinitario, 'price(100g)'] = (
    dark_chocolates.loc[has_Trinitario, 'price(100g)'] * 1.1
)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در مرحله‌ی آخر می‌خواهیم بدانیم در مجموع از فروش این شکلات‌های تلخ با قیمت‌هایی که مشخص کرده‌ایم چه‌قدر دریافت می‌کنیم. بنابراین مجموع قیمت شکلات‌های تلخ (ستون <code>price(100g)</code>) را محاسبه کرده و در متغیر <code>priceSum</code> ذخیره کنید.
</font>
</p>

In [80]:
priceSum = np.sum(dark_chocolates['price(100g)'])
priceSum

np.float64(96733662.5)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [81]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

df.to_csv('chocolate_price.csv', index = False)
dark_chocolates.to_csv('dark_chocolates.csv', index = True)

np.savez("answers.npz", has_Trinitario = has_Trinitario, priceSum = priceSum)
file_names = ["answers.npz", "chocolate_price.csv", "dark_chocolates.csv"]
compress(file_names)

File Paths:
['answers.npz', 'chocolate_price.csv', 'dark_chocolates.csv']